site_name: Kubernetes CI/CD Setup
nav:
- Docker:
  - docker/1-kurulum.md
  - docker/2-helloworld.md
  - docker/3-port.md
  - docker/4-volume.md
- Kubernetes: []
- CI/CD:
  - docker/index.md 
  - Page 1: section/page-1.md
  - Page n: section/page-n.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
